#Symfony app container
app:
  container_name: ct_back
  build: .    #Build the docker file
  command: bash -c 'php -S 0.0.0.0:80 -t /app/web && setfacl -d -m o::rwx /app/'
  links:
    - database
  ports:
    - 3000:80
  volumes:
    - ./ctest_apps:/app
#database container
database:
  container_name: ct_database
  image: mysql
  ports:
    - 5000:3306
  environment:
    MYSQL_ROOT_PASSWORD: erTYuiop_2017
    MYSQL_DATABASE: ctest_database
  volumes:
    - ./mysql_data:/var/lib/mysql
#phpmyadmin container
test_phpmyadmin:
  container_name: ct_phpmyadmin
  image: phpmyadmin/phpmyadmin
  ports:
    - 4000:80
  links:
    - database
  environment:
    - PMA_HOST=database
    - PMA_PORT=3306
    - PMA_USER=root
    - PMA_PASSWORD=erTYuiop_2017