web:
  build: .
  command: php -S 0.0.0.0:8000 -t /app
  links:
    - database
  ports:
    - "8000:8000"
  volumes:
    - ./ctest_apps:/app
database:
  image: mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: myapp
  volumes:
    - /mysql:/var/lib/mysql
test_phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - 8080:80
  links:
    - database
  environment:
    - PMA_HOST=database
    - PMA_PORT=3306
    - PMA_USER=root
    - PMA_PASSWORD=123456